version: "3.8"

services:
  mariadb:
    container_name: mariadb-container
    image: mariadb
    build: requirements/mariadb
    restart: always
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception
  
  nginx:
    container_name: nginx-container
    image: nginx
    build: requirements/nginx
    restart: always
    env_file: .env
    # Using port here because we also want to communicate with the host machine
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www
    networks:
      - inception
      
  wordpress:
    container_name: wordpress-container
    image: wordpress
    build: requirements/wordpress
    restart: always
    env_file: .env
    volumes:
      - wordpress:/var/www
    networks:
      - inception
    depends_on:
      - mariadb
  
volumes:
  wordpress:
    name: wordpress-volume
    driver_opts:
      type: volume
      device: /home/mliboz/data/wordpress
      o: bind
  mariadb:
    name: mariadb-volume
    driver_opts:
      type: volume
      device: /home/mliboz/data/mariadb
      o: bind
networks:
  inception:
    name: inception-network
